BRICK_DISTANCE = 1
SCREEN_MARGIN = 20
BORDER_WIDTH = 5
BOTTOM_BORDER_DISTANCE = 100

FRAMES_PER_SECOND = 60
WINDOW_TITLE = "*** pyNoid ***"
DEFAULT_RESOLUTION = (1280, 720)

START_BALL_SPEED = 7.0
CHECK_COLLISION_STEPS = 10
MAX_PADDLE_BOUNCE_ANGLE = 60
